project_id = "facextdabmrqllgdzkms"

[ai-operations]
verify_jwt = true

[security-scanner]
verify_jwt = true

[auth-operations]
verify_jwt = true

[execute-colab-cell]
verify_jwt = true

[ip-intelligence]
verify_jwt = true

[llm-operations]
verify_jwt = true

[send-notification]
verify_jwt = true