project_id = "facextdabmrqllgdzkms"

[ai-operations]
verify_jwt = true
import_map = "./import_map.json"

[analyze-apk]
verify_jwt = true

[security-scanner]
verify_jwt = true

[ip-intelligence]
verify_jwt = true