project_id = "facextdabmrqllgdzkms"

[functions.nuclei-scan]
verify_jwt = true

[functions.augment-prompts]
verify_jwt = true

[functions.huggingface-datasets]
verify_jwt = true

[functions.export-results]
verify_jwt = true