project_id = "facextdabmrqllgdzkms"

[functions.analyze-apk]
verify_jwt = true

[functions.ip-intelligence]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.view-apk-file]
verify_jwt = true

[functions.exchange-google-token]
verify_jwt = true

[functions.export-results]
verify_jwt = true

[functions.generate-finetuning-script]
verify_jwt = true

[functions.owasp-scan]
verify_jwt = true