project_id = "facextdabmrqllgdzkms"

[functions.owasp-scan]
verify_jwt = true

[functions.analyze-api]
verify_jwt = true

[functions.analyze-code-snippet]
verify_jwt = true

[functions.export-results]
verify_jwt = true

[functions.huggingface-datasets]
verify_jwt = true

[functions.init-colab-session]
verify_jwt = true

[functions.scheduled-llm-scan]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.ip-intelligence]
verify_jwt = true