project_id = "facextdabmrqllgdzkms"

[nuclei-scan]
verify_jwt = true

[domain-recon] 
verify_jwt = true

[ip-intelligence]
verify_jwt = true

[analyze-apk]
verify_jwt = true

[scan-github-repos]
verify_jwt = true