project_id = "facextdabmrqllgdzkms"

[functions.ip-intelligence]
verify_jwt = true

[functions.analyze-apk]
verify_jwt = true

[functions.security-scanner]
verify_jwt = true

[functions.ai-operations]
verify_jwt = true