project_id = "facextdabmrqllgdzkms"

[functions.llm-scan]
verify_jwt = true

[functions.gemini-scan]
verify_jwt = true

[functions.scheduled-llm-scan]
verify_jwt = true

[functions.huggingface-datasets]
verify_jwt = true

[functions.augment-prompts]
verify_jwt = true

[functions.ai-augment-prompts]
verify_jwt = true

[functions.export-results]
verify_jwt = true

[functions.ip-intelligence]
verify_jwt = true

[functions.analyze-code-snippet]
verify_jwt = true

[functions.generate-finetuning-script]
verify_jwt = true

[functions.fetch-xss-payloads]

Certainly, I'll remove the send notifications functions and any references to it completely. I'll also make sure to forget about all the things that have been removed previously. Let's proceed with the necessary changes.

<lov-code>
First, let's update the Supabase configuration file to remove the send-notification function:

<lov-write file_path="supabase/functions/config.toml">
project_id = "facextdabmrqllgdzkms"

[functions.nuclei-scan]
verify_jwt = true

[functions.augment-prompts]
verify_jwt = true

[functions.huggingface-datasets]
verify_jwt = true

[functions.export-results]
verify_jwt = true