project_id = "facextdabmrqllgdzkms"

[functions]
[functions.llm-scan]
verify_jwt = true

[functions.gemini-scan]
verify_jwt = true

[functions.scheduled-llm-scan]
verify_jwt = true

[functions.huggingface-datasets]
verify_jwt = true

[functions.augment-prompts]
verify_jwt = true

[functions.ai-augment-prompts]
verify_jwt = true

[functions.export-results]
verify_jwt = true

[functions.ip-intelligence]
verify_jwt = true

[functions.analyze-code-snippet]
verify_jwt = true

[functions.generate-finetuning-script]
verify_jwt = true

[functions.fetch-xss-payloads]
verify_jwt = true

[functions.execute-colab-cell]
verify_jwt = true

[functions.init-colab-session]
verify_jwt = true

[functions.exchange-google-token]
verify_jwt = true

[functions.scan-github-repos]
verify_jwt = true

[functions.llm-operations]
verify_jwt = true

[functions.chat-support]
verify_jwt = true